server:
  port: 8089

spring:
  mvc:
    async:
      request-timeout: 60000
  application:
    name: mcp-name
  ai:
    bailian:
      api-key: sk-5a839dbb64074a62a1a78e9cb6502bef  # 你的 DashScope API Key
      model: qwen-max                # 可选：qwen-plus, qwen-turbo 等

ai:
  mcp:
    server:
      name: mcp-name
      version: 1.0.0
      type: SYNC
      sse-endpoint: /sse


# 阿里云百炼 MCP 配置
mcp:
  websearch:
    base-url: https://dashscope.aliyuncs.com/api/v1/mcps/WebSearch/sse
    api-key: sk-5a839dbb64074a62a1a78e9cb6502bef  # 设置环境变量或配置文件中


qwenkey: sk-5a839dbb64074a62a1a78e9cb6502bef

smd:
  service:
    url: http://localhost:8081/api

news:
  service:
    url: http://localhost:8081/api